package iutbayonne.projet.zicall.EcriturePartitionPackage;

import iutbayonne.projet.zicall.R;

public enum SourceImageNotePartition
{
    PARTITION_VIERGE(R.drawable.partition_vierge),
    DEBUT_LIGNE(R.drawable.debut_ligne),
    FIN_LIGNE(R.drawable.fin_ligne),
    FIN_PARTITION(R.drawable.fin_partition),
    NOTE_EN_COURS_MODIFICATION(R.drawable.image_note_en_cours_de_modification),
    NOTE_JOUEE(R.drawable.note_jouee),

    DO_GAMME_1_CROCHE(R.drawable.do_gamme_1_croche),
    DO_GAMME_1_NOIRE(R.drawable.do_gamme_1_noire),
    DO_GAMME_1_BLANCHE(R.drawable.do_gamme_1_blanche),
    DO_GAMME_1_RONDE(R.drawable.do_gamme_1_ronde),
    RE_GAMME_1_CROCHE(R.drawable.re_gamme_1_croche),
    RE_GAMME_1_NOIRE(R.drawable.re_gamme_1_noire),
    RE_GAMME_1_BLANCHE(R.drawable.re_gamme_1_blanche),
    RE_GAMME_1_RONDE(R.drawable.re_gamme_1_ronde),
    MI_GAMME_1_CROCHE(R.drawable.mi_gamme_1_croche),
    MI_GAMME_1_NOIRE(R.drawable.mi_gamme_1_noire),
    MI_GAMME_1_BLANCHE(R.drawable.mi_gamme_1_blanche),
    MI_GAMME_1_RONDE(R.drawable.mi_gamme_1_ronde),
    FA_GAMME_1_CROCHE(R.drawable.fa_gamme_1_croche),
    FA_GAMME_1_NOIRE(R.drawable.fa_gamme_1_noire),
    FA_GAMME_1_BLANCHE(R.drawable.fa_gamme_1_blanche),
    FA_GAMME_1_RONDE(R.drawable.fa_gamme_1_ronde),
    SOL_GAMME_1_CROCHE(R.drawable.sol_gamme_1_croche),
    SOL_GAMME_1_NOIRE(R.drawable.sol_gamme_1_noire),
    SOL_GAMME_1_BLANCHE(R.drawable.sol_gamme_1_blanche),
    SOL_GAMME_1_RONDE(R.drawable.sol_gamme_1_ronde),
    LA_GAMME_1_CROCHE(R.drawable.la_gamme_1_croche),
    LA_GAMME_1_NOIRE(R.drawable.la_gamme_1_noire),
    LA_GAMME_1_BLANCHE(R.drawable.la_gamme_1_blanche),
    LA_GAMME_1_RONDE(R.drawable.la_gamme_1_ronde),
    SI_GAMME_1_CROCHE(R.drawable.si_gamme_1_croche),
    SI_GAMME_1_NOIRE(R.drawable.si_gamme_1_noire),
    SI_GAMME_1_BLANCHE(R.drawable.si_gamme_1_blanche),
    SI_GAMME_1_RONDE(R.drawable.si_gamme_1_ronde),
    DO_DIESE_GAMME_1_CROCHE(R.drawable.do_diese_gamme_1_croche),
    DO_DIESE_GAMME_1_NOIRE(R.drawable.do_diese_gamme_1_noire),
    DO_DIESE_GAMME_1_BLANCHE(R.drawable.do_diese_gamme_1_blanche),
    DO_DIESE_GAMME_1_RONDE(R.drawable.do_diese_gamme_1_ronde),
    RE_DIESE_GAMME_1_CROCHE(R.drawable.re_diese_gamme_1_croche),
    RE_DIESE_GAMME_1_NOIRE(R.drawable.re_diese_gamme_1_noire),
    RE_DIESE_GAMME_1_BLANCHE(R.drawable.re_diese_gamme_1_blanche),
    RE_DIESE_GAMME_1_RONDE(R.drawable.re_diese_gamme_1_ronde),
    FA_DIESE_GAMME_1_CROCHE(R.drawable.fa_diese_gamme_1_croche),
    FA_DIESE_GAMME_1_NOIRE(R.drawable.fa_diese_gamme_1_noire),
    FA_DIESE_GAMME_1_BLANCHE(R.drawable.fa_diese_gamme_1_blanche),
    FA_DIESE_GAMME_1_RONDE(R.drawable.fa_diese_gamme_1_ronde),
    SOL_DIESE_GAMME_1_CROCHE(R.drawable.sol_diese_gamme_1_croche),
    SOL_DIESE_GAMME_1_NOIRE(R.drawable.sol_diese_gamme_1_noire),
    SOL_DIESE_GAMME_1_BLANCHE(R.drawable.sol_diese_gamme_1_blanche),
    SOL_DIESE_GAMME_1_RONDE(R.drawable.sol_diese_gamme_1_ronde),
    LA_DIESE_GAMME_1_CROCHE(R.drawable.la_diese_gamme_1_croche),
    LA_DIESE_GAMME_1_NOIRE(R.drawable.la_diese_gamme_1_noire),
    LA_DIESE_GAMME_1_BLANCHE(R.drawable.la_diese_gamme_1_blanche),
    LA_DIESE_GAMME_1_RONDE(R.drawable.la_diese_gamme_1_ronde),

    DO_GAMME_0_CROCHE(R.drawable.do_gamme_0_croche),
    DO_GAMME_0_NOIRE(R.drawable.do_gamme_0_noire),
    DO_GAMME_0_BLANCHE(R.drawable.do_gamme_0_blanche),
    DO_GAMME_0_RONDE(R.drawable.do_gamme_0_ronde),
    RE_GAMME_0_CROCHE(R.drawable.re_gamme_0_croche),
    RE_GAMME_0_NOIRE(R.drawable.re_gamme_0_noire),
    RE_GAMME_0_BLANCHE(R.drawable.re_gamme_0_blanche),
    RE_GAMME_0_RONDE(R.drawable.re_gamme_0_ronde),
    MI_GAMME_0_CROCHE(R.drawable.mi_gamme_0_croche),
    MI_GAMME_0_NOIRE(R.drawable.mi_gamme_0_noire),
    MI_GAMME_0_BLANCHE(R.drawable.mi_gamme_0_blanche),
    MI_GAMME_0_RONDE(R.drawable.mi_gamme_0_ronde),
    FA_GAMME_0_CROCHE(R.drawable.fa_gamme_0_croche),
    FA_GAMME_0_NOIRE(R.drawable.fa_gamme_0_noire),
    FA_GAMME_0_BLANCHE(R.drawable.fa_gamme_0_blanche),
    FA_GAMME_0_RONDE(R.drawable.fa_gamme_0_ronde),
    SOL_GAMME_0_CROCHE(R.drawable.sol_gamme_0_croche),
    SOL_GAMME_0_NOIRE(R.drawable.sol_gamme_0_noire),
    SOL_GAMME_0_BLANCHE(R.drawable.sol_gamme_0_blanche),
    SOL_GAMME_0_RONDE(R.drawable.sol_gamme_0_ronde),
    LA_GAMME_0_CROCHE(R.drawable.la_gamme_0_croche),
    LA_GAMME_0_NOIRE(R.drawable.la_gamme_0_noire),
    LA_GAMME_0_BLANCHE(R.drawable.la_gamme_0_blanche),
    LA_GAMME_0_RONDE(R.drawable.la_gamme_0_ronde),
    SI_GAMME_0_CROCHE(R.drawable.si_gamme_0_croche),
    SI_GAMME_0_NOIRE(R.drawable.si_gamme_0_noire),
    SI_GAMME_0_BLANCHE(R.drawable.si_gamme_0_blanche),
    SI_GAMME_0_RONDE(R.drawable.si_gamme_0_ronde),
    DO_DIESE_GAMME_0_CROCHE(R.drawable.do_diese_gamme_0_croche),
    DO_DIESE_GAMME_0_NOIRE(R.drawable.do_diese_gamme_0_noire),
    DO_DIESE_GAMME_0_BLANCHE(R.drawable.do_diese_gamme_0_blanche),
    DO_DIESE_GAMME_0_RONDE(R.drawable.do_diese_gamme_0_ronde),
    RE_DIESE_GAMME_0_CROCHE(R.drawable.re_diese_gamme_0_croche),
    RE_DIESE_GAMME_0_NOIRE(R.drawable.re_diese_gamme_0_noire),
    RE_DIESE_GAMME_0_BLANCHE(R.drawable.re_diese_gamme_0_blanche),
    RE_DIESE_GAMME_0_RONDE(R.drawable.re_diese_gamme_0_ronde),
    FA_DIESE_GAMME_0_CROCHE(R.drawable.fa_diese_gamme_0_croche),
    FA_DIESE_GAMME_0_NOIRE(R.drawable.fa_diese_gamme_0_noire),
    FA_DIESE_GAMME_0_BLANCHE(R.drawable.fa_diese_gamme_0_blanche),
    FA_DIESE_GAMME_0_RONDE(R.drawable.fa_diese_gamme_0_ronde),
    SOL_DIESE_GAMME_0_CROCHE(R.drawable.sol_diese_gamme_0_croche),
    SOL_DIESE_GAMME_0_NOIRE(R.drawable.sol_diese_gamme_0_noire),
    SOL_DIESE_GAMME_0_BLANCHE(R.drawable.sol_diese_gamme_0_blanche),
    SOL_DIESE_GAMME_0_RONDE(R.drawable.sol_diese_gamme_0_ronde),
    LA_DIESE_GAMME_0_CROCHE(R.drawable.la_diese_gamme_0_croche),
    LA_DIESE_GAMME_0_NOIRE(R.drawable.la_diese_gamme_0_noire),
    LA_DIESE_GAMME_0_BLANCHE(R.drawable.la_diese_gamme_0_blanche),
    LA_DIESE_GAMME_0_RONDE(R.drawable.la_diese_gamme_0_ronde);

    /**
     *  Identifiant de l'image qui correspond à la note.
     */
    private int sourceImage;

    SourceImageNotePartition(int sourceImage) {
        this.sourceImage = sourceImage;
    }

    public int getSourceImage(){return sourceImage;}
}
